export const STUDENT_SIGNUP = "STUDENT_SIGNUP";
export const TEACHER_SIGNUP = "TEACHER_SIGNUP";
export const ADMIN_SIGNUP = "ADMIN_SIGNUP";

export const PASSWORD_UPDATE_SUCCESS = "PASSWORD_UPDATE_SUCCESS";
export const DELETE_SUCCESS = "DELETE_SUCCESS";

export const UPDATE_ERROR = "UPDATE_ERROR";
export const UPDATE_DATA_SUCCESS = "UPDATE_DATA_SUCCESS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";
